# Generated by Django 4.1.9 on 2023-12-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_bank',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
