# Generated by Django 4.2.1 on 2023-10-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_blood_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='user_details',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='Home.user_details'),
            preserve_default=False,
        ),
    ]
