# Generated by Django 5.0 on 2023-12-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
