# Generated by Django 4.1.9 on 2023-12-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievement_images/')),
            ],
        ),
    ]
